### PR TITLE
Dockerise everything!

### PR DESCRIPTION
**Pull request by matthew5025**
This aims to simplify the deployment of this application through containerisation.

### CODE REVIEW

**Comment by matthew5025** [comment]
At this stage, the application should be deployable with a simple docker-compose up
This will break non docker hosting, so it is not fit for merging atm.
TBD

- [ ] Automated secret and salt generation
- [ ] Deployment nginx config
- [ ] Feel free to add anything else

**Comment by 152334H** [comment]
does not work on my machine 👎

**Comment by matthew5025** [comment]
@152334H Seems like the context was required. Could you pull and try again?

**Review by 152334H — APPROVED** [review]
good shit

---

> Should an admin account be automatically generated on first deployment?
 
I want to say yes, but this kind of thing has been historically considered as a bug on other CTF platforms (like CTFd <= 2.1.5).

You could add a mandatory env var for admin credentials, or maybe generate a randomized password to be displayed when building the container?

> Is docker going to be the preferred way for deployment going forward?

The lead developer for this project says: at least not for IRS-cybersec. 🤷 

Docker is definitely more simple for me, but I am not a web-developer anyway.

**Comment by matthew5025** [comment]
> You could add a mandatory env var for admin credentials, or maybe generate a randomized password to be displayed when building the container?

I think that would be the best; perhaps on first run rather than building.
Might do the same to the env secrets; I think in general it is better for the app to be secure by default rather than rely on the user to change the default values to make it secure

**Comment by matthew5025** [comment]
@Tkaixiang fyi i changed some stuff so you might want to stash your changes b4 you merge

**Comment by matthew5025** [comment]
> Should an admin account be automatically generated on first deployment?

This is tracked using PR #93

**Comment by matthew5025** [comment]
Secret and salt generation tracked in #94

**Comment by Tkaixiang** [comment]
Looks good to me

**Comment by matthew5025** [comment]
# Test Results

## Bare Metal 

- [x] API Server Starts

- [x] Admin credentials generated

### Notes
1. **ctf_platform\api\utils\mongoDB.js**
`mongodb://ctf-mongodb:27017` needs to be changed to `mongodb://localhost:27017`

## Local Docker Compose (Windows)

- [x] Docker Compose builds

- [x] Docker Compose comes up

- [x] Web UI accessible over localhost:20002

- [x] Admin credentials generated

- [x] Logs in to Admin account with generated credentials

- [x] Scoreboard websocket connects


## Hosted Docker Compose (Ubuntu 20.04 (LTS) x64)

- [x] Git pull succeeds

- [x] Docker Compose builds

- [x] Docker Compose comes up

- [x] Nginx configuration `ctf_platform.conf` is valid in the `sites-enabled` folder

- [x] Web UI accessible through `http://ctf.nat.ninja`

- [x] Admin credentials generated

- [x] Logs in to Admin account with generated credentials

- [x] Scoreboard websocket connects

- [x] Certbot succeeds in issusing and installing HTTPS cert

- [x] HTTP to HTTPS redirection works

- [x] Web UI accessible through `https://ctf.nat.ninja`

- [x] Logs in to Admin account with generated credentials over HTTPS

- [x] Scoreboard websocket connects over wss

### Notes
1. **ctf_platform\ctf_platform.conf**
`server_name ctf.example.com` needs to be changed to your desired domain

**Comment by matthew5025** [comment]
LGTM

**Comment by Tkaixiang** [comment]
LGTM, great job 😄 !

**Pull request merged**
